pe-newstyle-factor-35
mmerickel/wired pull request #38
Opened 2020-06-29 01:32 UTC by pauleveritt

First draft of the factory proposal's science fiction.

2020-07-08 02:22 UTC, mmerickel commented on docs/factories.rst
> +But that's a big surface are -- the entire ``Customer`` -- when the contract really only wants one piece of data.
area

2020-07-08 02:25 UTC, mmerickel commented on docs/factories.rst
> +            return html('<div>Hello {self.name}{self.punctuation}'
missing `)`

2020-07-08 02:26 UTC, mmerickel commented on docs/factories.rst
> +    Injected = Annotated[LT, RT, Injector]
This is getting pretty wild for me as someone who is barely even using typing. It's interesting though!

2020-09-07 00:46 UTC, pauleveritt commented
@mmerickel I split out the science fiction for factory and injector. We can focus on the former. Jim has offered to help me on some decorator and Signature stuff.

The last two sections in `factories.rst` have some changed points which I'm curious whether you are ok on. It's about functions instead of classes.

2020-09-07 18:35 UTC, pauleveritt commented
I pushed an implementation of the science fiction with a bunch of tests.

2020-10-10 23:31 UTC, mmerickel requested changes

2020-10-10 23:31 UTC, mmerickel commented on docs/factories.rst
> +In the existing ``wired``, registering a factory means is a method call on the registry:
"means is a" ?

2020-10-10 23:31 UTC, mmerickel commented on docs/factories.rst
> +Meaning, the class *constructor* is entirety of the factory.
is "the" entirety

2020-10-10 23:31 UTC, mmerickel commented on docs/factories.rst
> +    registry.register_service(LoginService)
This is taking things a step too far and coupling the interface/context/name into a "service descriptor" which is a combination of `(factory, interface, context, name)`. I thought the plan was just to focus on the factory part of that and making it easier to define.

2020-10-11 20:34 UTC, pauleveritt commented
As discussed in chat, I will retract this PR. Individual pieces might resurface later in easier-to-digest chunks.

2020-10-11 20:34 UTC, closed without merging